name:  PushToDocker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
   runs-on: ubuntu-20.04
   steps:
      - uses: actions/checkout@v2
      - run:  bash thine.sh
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: itsvixano/ci_docker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          buildoptions: --force-rm --compress --no-cache --squash
          tags: "latest"
